name = "adoptimize"
main = ".open-next/worker.js"
compatibility_date = "2026-03-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[routes]]
pattern = "adoptimize.1wayseo.com"
custom_domain = true

[vars]
ENVIRONMENT = "production"
PYTHON_API_URL = "https://adoptimize-api.fly.dev"
