# -*- coding: utf-8 -*-
"""
Backend Services Module

導出計算服務和工具類
"""

from app.services.audit_engine import (
    AuditGrade,
    AuditInput,
    AuditIssue,
    AuditScoreResult,
    DimensionInput,
    DimensionScoreResult,
    IssueCategory,
    IssueSeverity,
    AUDIT_WEIGHTS,
    AUDIT_GRADE_THRESHOLDS,
    ALL_ISSUES,
    STRUCTURE_ISSUES,
    CREATIVE_ISSUES,
    AUDIENCE_ISSUES,
    BUDGET_ISSUES,
    TRACKING_ISSUES,
    calculate_audit_score,
    calculate_dimension_score,
    get_audit_grade,
    get_issue_by_code,
    create_issue_with_entities,
)

from app.services.fatigue_score import (
    FatigueBreakdown,
    FatigueInput,
    FatigueResult,
    FatigueStatus,
    FATIGUE_WEIGHTS,
    FATIGUE_THRESHOLDS,
    calculate_ctr_score,
    calculate_conversion_score,
    calculate_days_score,
    calculate_fatigue_score,
    calculate_frequency_score,
    get_fatigue_status,
)

from app.services.redis_client import RedisClient, get_redis_client

from app.services.audience_health import (
    AudienceHealthBreakdown,
    AudienceHealthInput,
    AudienceHealthResult,
    AudienceHealthStatus,
    AUDIENCE_HEALTH_WEIGHTS,
    AUDIENCE_HEALTH_THRESHOLDS,
    SIZE_THRESHOLDS,
    CPA_THRESHOLDS,
    ROAS_THRESHOLDS,
    FRESHNESS_THRESHOLDS,
    calculate_size_score,
    calculate_cpa_score,
    calculate_roas_score,
    calculate_freshness_score,
    calculate_audience_health,
    get_audience_health_status,
)

from app.services.recommendation_engine import (
    ActionDifficulty,
    ActionModule,
    ActionParams,
    Recommendation,
    RecommendationStatus,
    SEVERITY_BASE_SCORES,
    DIFFICULTY_SCORES,
    MAX_IMPACT_SCORE,
    ENTITY_SCORE,
    calculate_priority_score,
    get_action_module_for_issue,
    get_difficulty_for_action,
    estimate_impact,
    create_recommendation_from_issue,
    generate_recommendations_from_issues,
    filter_recommendations,
)

from app.services.token_manager import TokenManager

__all__ = [
    # Audit Engine
    "AuditGrade",
    "AuditInput",
    "AuditIssue",
    "AuditScoreResult",
    "DimensionInput",
    "DimensionScoreResult",
    "IssueCategory",
    "IssueSeverity",
    "AUDIT_WEIGHTS",
    "AUDIT_GRADE_THRESHOLDS",
    "ALL_ISSUES",
    "STRUCTURE_ISSUES",
    "CREATIVE_ISSUES",
    "AUDIENCE_ISSUES",
    "BUDGET_ISSUES",
    "TRACKING_ISSUES",
    "calculate_audit_score",
    "calculate_dimension_score",
    "get_audit_grade",
    "get_issue_by_code",
    "create_issue_with_entities",
    # Fatigue Score
    "FatigueBreakdown",
    "FatigueInput",
    "FatigueResult",
    "FatigueStatus",
    "FATIGUE_WEIGHTS",
    "FATIGUE_THRESHOLDS",
    "calculate_ctr_score",
    "calculate_conversion_score",
    "calculate_days_score",
    "calculate_fatigue_score",
    "calculate_frequency_score",
    "get_fatigue_status",
    # Redis
    "RedisClient",
    "get_redis_client",
    # Audience Health
    "AudienceHealthBreakdown",
    "AudienceHealthInput",
    "AudienceHealthResult",
    "AudienceHealthStatus",
    "AUDIENCE_HEALTH_WEIGHTS",
    "AUDIENCE_HEALTH_THRESHOLDS",
    "SIZE_THRESHOLDS",
    "CPA_THRESHOLDS",
    "ROAS_THRESHOLDS",
    "FRESHNESS_THRESHOLDS",
    "calculate_size_score",
    "calculate_cpa_score",
    "calculate_roas_score",
    "calculate_freshness_score",
    "calculate_audience_health",
    "get_audience_health_status",
    # Recommendation Engine
    "ActionDifficulty",
    "ActionModule",
    "ActionParams",
    "Recommendation",
    "RecommendationStatus",
    "SEVERITY_BASE_SCORES",
    "DIFFICULTY_SCORES",
    "MAX_IMPACT_SCORE",
    "ENTITY_SCORE",
    "calculate_priority_score",
    "get_action_module_for_issue",
    "get_difficulty_for_action",
    "estimate_impact",
    "create_recommendation_from_issue",
    "generate_recommendations_from_issues",
    "filter_recommendations",
    # Token Manager
    "TokenManager",
]
